# Rename this file to config.yaml

accounts:
  - email: prenm.nom@edu.devinci.fr
    pass: TonMotDePasse
    freq:
      grades: 30
      presence: 5
      promotions: 5
      error: 120
    hooks:
      - triggers:
        - type: presence
          events:
            # - "*" # all the events below
            - opened # when teacher opened presence
            - closed # when teacher closed presence
            # - student:ok # when student validated his presence
            # - student:absent # when student did not validate his presence / is set absent, triggered at the end of the presence
            # - course:started # when the course started
            # - course:ended # when the course ended
          group_prefix: ESILV-
        - type: grades # experimental
          events:
            - grade:created # when an exam is added
            - grade:set # when a grade is available
            - grade:updated # when a grade is changed
            - grade:rattrapage:set # when a rattrapage grade is available
          min_update_delta: 1 # only send grade:updated events when abs(new-old)>=delta
        - type: promotions
          events:
            - created
          skip_alumni_events: true
        mode: DiscordWebHookV1
        url: https://discordapp.com/api/webhooks/...

      - triggers:
          - type: grades
            events: ["*"]
            hidden_fields: ['units', 'subjects', 'grades']
            show_minor_updates: true
        mode: DiscordWebHookV1
        url: https://discordapp.com/api/webhooks/...

  # - email: nom2.prenom2@edu.devinci.fr
  #   pass: "MotDePasseCompte2"
  #   freq:
  #     grades: 30
  #     presence: 5
  #     error: 120
  #   hooks: []


# Don't touch these unless you know what you are doing
log_level: INFO
cookies_cache: data/cookies_{id}.cache
grades_cache: data/grades_{id}.json
promotions_cache: data/promotions_{id}.json
timezone: Europe/Paris